### ISSUE TITLE
Can't log in or register at deployed Heroku site

### ISSUE THREAD

**Issue by denisemariel** [CS192-CalNotes/CalNotes#18] opened 2021-06-02 03:26 UTC
![image](https://user-images.githubusercontent.com/42923784/120419658-6c553900-c395-11eb-9250-3d76d6a69f25.png)

**Comment by JustroX** [comment] 2021-06-02 06:26
Probably caused by different dev/prod environment setting. Will be fixed by merging #19

**Closed as completed** 2021-06-02 06:29 UTC
